### PR TITLE
Release 4.5.0

### PR DESCRIPTION
**Pull request by minrk**
also re-rendered

### CODE REVIEW

**Comment by minrk** [comment]
What's the best way to handle simultaneous release series (node 5,6)? Separate feedstock, branches on the feedstock, or PRs with non-monotonic version changes?

**Comment by ocefpaf** [comment]
> What's the best way to handle simultaneous release series (node 5,6)? Separate feedstock, branches on the feedstock, or PRs with non-monotonic version changes?

Separate branches on the same feedstock. (We are using that in the the gdal and django feedstocks.)

**Comment by minrk** [comment]
Perfect, thanks. Would it be helpful to add myself as a maintainer on this repo?

**Comment by ocefpaf** [comment]
> Would it be helpful to add myself as a maintainer on this repo?

Always!

**Comment by ocefpaf** [comment]
> Always!

Argh! Clicker merged before thinking... It would be easier for you to add yourself in this PR! Sorry.

**Comment by minrk** [comment]
@ocefpaf I was thinking the same thing. Do I need to bump the build number to add myself?

**Comment by ocefpaf** [comment]
> @ocefpaf I was thinking the same thing. Do I need to bump the build number to add myself?

Not necessarily. I never do but some people like to get their name in the package metadata ASAP so they do bump. Your choice.

**Comment by minrk** [comment]
OK, then I'll make a 4.x branch with a copy of current master, then open a PR to point master to 6.x. Does that sound like the right route? I'll do this tomorrow, as it's getting toward the end of the day here.

**Comment by ocefpaf** [comment]
> OK, then I'll make a 4.x branch with a copy of current master, then open a PR to point master to 6.x. Does that sound like the right route? I'll do this tomorrow, as it's getting toward the end of the day here.

Yep. If you cannot create the branch (sometimes the bot may take a while to process your addition to the feedstock) just ping me and I will do that for you.

**Pull request merged**
