### PR TITLE
Build shared library

### LINKED ISSUE #114: Not building linux-ppc
Linux ppc builds have been failing for a while now, due to a couple of reasons. 

1. it has previously exceeded the time limit (1h) on Travis. I tried on Azure, but due to emulation it *also* exceeds the much greater time limit there (6h, #101)
2. Compilation is [now](https://travis-ci.com/conda-forge/nodejs-feedstock/builds/143696707) crashing with:

    ```
    $BUILD_PREFIX/bin/powerpc64le-conda_cos7-linux-gnu-c++ -o $SRC_DIR/out/Release/obj.target/v8_compiler/deps/v8/src/compiler/branch-elimination.o ../deps/v8/src/compiler/branch-elimination.cc '-DV8_GYP_BUILD' '-DV8_TYPED_ARRAY_MAX_SIZE_IN_HEAP=64' '-D__STDC_FORMAT_MACROS' '-DV8_TARGET_ARCH_PPC' '-DV8_TARGET_ARCH_PPC64' '-DV8_TARGET_ARCH_PPC_LE' '-DV8_EMBEDDER_STRING="-node.26"' '-DENABLE_DISASSEMBLER' '-DV8_PROMISE_INTERNAL_FIELD_COUNT=1' '-DENABLE_MINOR_MC' '-DV8_INTL_SUPPORT' '-DV8_CONCURRENT_MARKING' '-DV8_ENABLE_LAZY_SOURCE_POSITIONS' '-DV8_EMBEDDED_BUILTINS' '-DV8_USE_SIPHASH' '-DDISABLE_UNTRUSTED_CODE_MITIGATIONS' '-DV8_WIN64_UNWINDING_INFO' '-DV8_ENABLE_REGEXP_INTERPRETER_THREADED_DISPATCH' -I$PREFIX/include -I../deps/v8 -I../deps/v8/include -I$SRC_DIR/out/Release/obj/gen/generate-bytecode-output-root -I$SRC_DIR/out/Release/obj/gen/torque-output-root  -pthread -Wno-unused-parameter -m64 -mminimal-toc -Wno-return-type -fno-strict-aliasing -m64 -O3 -fno-omit-frame-pointer -fdata-sections -ffunction-sections -O3 -fno-rtti -fno-exceptions -std=gnu++1y -MMD -MF $SRC_DIR/out/Release/.deps/$SRC_DIR/out/Release/obj.target/v8_compiler/deps/v8/src/compiler/branch-elimination.o.d.raw -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -fvisibility-inlines-hidden  -fmessage-length=0 -mcpu=power8 -mtune=power8 -mpower8-fusion -mpower8-vector -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/nodejs-13.6.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -c
    /home/conda/feedstock_root/.scripts/build_steps.sh: line 33:   756 Killed                  conda build "${RECIPE_ROOT}" -m "${CI_SUPPORT}/${CONFIG}.yaml" --clobber-file "${CI_SUPPORT}/clobber_${CONFIG}.yaml"
    powerpc64le-conda_cos7-linux-gnu-c++: fatal error: Killed signal terminated program cc1plus
    compilation terminated.
    powerpc64le-conda_cos7-linux-gnu-c++: fatal error: Killed signal terminated program cc1plus
    compilation terminated.
    ```

   which I am guessing indicates the compiler running out of RAM

### PR DESCRIPTION
**Pull request by xhochy**
Fixes #114 

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xhochy** [comment]
@conda-forge-admin please rerender

**Comment by xhochy** [comment]
@conda-forge-admin please rerender

**Comment by xhochy** [comment]
@conda-forge/staged-recipes This is ready for review/merge.

**Comment by SylvainCorlay** [comment]
Wow, this is impressive!

Really happy to see this happen.

**Comment by jakirkham** [comment]
Thanks @xhochy! 😄

**Pull request merged**
