### PR TITLE
Bump to 10.2.1, use new compilers, nasm for windows, rerender

### PR DESCRIPTION
**Pull request by bollwyvl**
Following suggestion on #37, this adds `nasm`on windows.

### CODE REVIEW

**Comment by jasongrout** [comment]
Note that the currently-released JupyterLab doesn't work well with nodejs 10.

**Comment by minrk** [comment]
Does jupyterlab have a dependency on nodejs in conda? If so, it should probably be pinning down the nodejs dependency to `<10`

**Comment by jasongrout** [comment]
> Does jupyterlab have a dependency on nodejs in conda? If so, it should probably be pinning down the nodejs dependency to <10

JupyterLab does not have a hard dependency on node, since we only need nodejs for installing extensions. This problem will be resolved in the next version of jlab, though (we upgrade yarn, which was the problem).

**Comment by minrk** [comment]
Fixed cb3 update in #44

**Pull request closed without merging**
