### PR TITLE
Enable building with Python 3.7

### PR DESCRIPTION
**Pull request by jarkkorantala**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xhochy** [comment]
What's the reason for this?

**Comment by jarkkorantala** [comment]
If there's no barriers to building in Python 3.7, the idea is for this to enable using the package in environments that can't use Python 3.8 for other reasons.

**Comment by xhochy** [comment]
The resulting package should have no dependency/constraint on Python at all as we only have `python` in the build section.

**Comment by xhochy** [comment]
If I create a environment with only `nodejs` I get the following resolution:

```
  Package            Version  Build          Channel                     Size
───────────────────────────────────────────────────────────────────────────────
  Install:
───────────────────────────────────────────────────────────────────────────────

  ca-certificates  2020.12.5  h4653dfc_0     conda-forge/osx-arm64     Cached
  icu                   68.1  h17758a7_0     conda-forge/osx-arm64     Cached
  libcxx              11.1.0  h168391b_0     conda-forge/osx-arm64     Cached
  libuv               1.41.0  h27ca646_0     conda-forge/osx-arm64     Cached
  nodejs             15.14.0  hcd5e986_0     conda-forge/osx-arm64      12 MB
  openssl             1.1.1k  h27ca646_0     conda-forge/osx-arm64     Cached
  zlib                1.2.11  h31e879b_1009  conda-forge/osx-arm64     Cached
  ```

Including `python=3.9` in the specs leads to 

```
  Package            Version  Build               Channel                     Size
────────────────────────────────────────────────────────────────────────────────────
  Install:
────────────────────────────────────────────────────────────────────────────────────

  ca-certificates  2020.12.5  h4653dfc_0          conda-forge/osx-arm64     Cached
  certifi          2020.12.5  py39h2804cbe_1      conda-forge/osx-arm64     Cached
  icu                   68.1  h17758a7_0          conda-forge/osx-arm64     Cached
  libcxx              11.1.0  h168391b_0          conda-forge/osx-arm64     Cached
  libuv               1.41.0  h27ca646_0          conda-forge/osx-arm64     Cached
  ncurses                6.2  h9aa5885_4          conda-forge/osx-arm64     Cached
  nodejs             15.14.0  hcd5e986_0          conda-forge/osx-arm64      12 MB
  openssl             1.1.1k  h27ca646_0          conda-forge/osx-arm64     Cached
  pip                 21.0.1  pyhd8ed1ab_0        conda-forge/noarch        Cached
  python               3.9.2  hcbd9b3a_0_cpython  conda-forge/osx-arm64     Cached
  python_abi             3.9  1_cp39              conda-forge/osx-arm64     Cached
  readline               8.1  hfbdcbf2_0          conda-forge/osx-arm64     Cached
  setuptools          49.6.0  py39h2804cbe_3      conda-forge/osx-arm64     Cached
  sqlite              3.35.4  hc49ca36_0          conda-forge/osx-arm64     Cached
  tk                  8.6.10  hf7e6567_1          conda-forge/osx-arm64     Cached
  tzdata               2021a  he74cb21_0          conda-forge/noarch        Cached
  wheel               0.36.2  pyhd3deb0d_0        conda-forge/noarch        Cached
  xz                   5.2.5  h642e427_1          conda-forge/osx-arm64     Cached
  zlib                1.2.11  h31e879b_1009       conda-forge/osx-arm64     Cached
  ```
  
Thus the explicit pin is no issue.

**Comment by jarkkorantala** [comment]
Thanks - I think I was just arriving at the same resolution. I'll investigate my issue with our local Conda repository a little more, it's probably not due to this.

**Comment by jarkkorantala** [comment]
This pull request turned to be unnecessary as previously discussed. Thanks for the feedback!

**Pull request closed without merging**
