### PR TITLE
node 8: windows

### PR DESCRIPTION
**Pull request by minrk**

### CODE REVIEW

**Comment by minrk** [comment]
Huzzah!

**Comment by gregfreeman** [comment]
Excellent that this is fixed!  Thanks!  What's the next step to get windows packages on the conda-forge conda channel?

**Comment by minrk** [comment]
Arg! I thought I fixed the Windows builds, but the green check mark is a lie. Appveyor tests just didn't run for some reason. #19 should fix the Windows builds.

**Comment by minrk** [comment]
#19 is fixed, node 8 should be published on Windows within an hour or two.

**Pull request merged**
