### PR TITLE
updated v14.15.4

### PR DESCRIPTION
**Pull request by blabalme**
New version v14.15.4

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Review by xhochy — APPROVED** [review]

**Comment by xhochy** [comment]
Looks like the patches need to be rebased, too.

**Comment by blabalme** [comment]
@conda-forge-admin, please rerender

**Comment by blabalme** [comment]
I found this exemple to fix it : https://github.com/cweagans/composer-patches/pull/184.

**Comment by blabalme** [comment]
the error comes from "linux-install.patch" but this file is not in the project. @xhochy what do you mean by "patches need to be rebased" ?

**Comment by blabalme** [comment]
I found original commit for `linux-install.patch` :  https://github.com/conda-forge/nodejs-feedstock/commit/0f6949040f0316ac83cf01a9869b0aafef46bb7e

but I don't understand why it comes back when CI does the command `git checkout --progress --force refs/remotes/pull/171/merge`

**Comment by blabalme** [comment]
I try to ckeckout --force my fork ,remove linux-install.patch and update meta.yaml
it only solves one problem, I don't know if this is the good solution ...

**Review by minrk — APPROVED** [review]

**Pull request merged**
