### PR TITLE
13.6

### PR DESCRIPTION
**Pull request by minrk**

### CODE REVIEW

**Comment by blink1073** [comment]
Perhaps we need `-std=gnu99`?  cf https://stackoverflow.com/questions/5446698/map-anonymous-with-c99-standard and https://github.com/conda-forge/nodejs-feedstock/commit/a60d4ee238362167a67ba80a9f709bd47b049f95#diff-44a73bcc045c193c3bd45da87994b03b

**Comment by minrk** [comment]
node uses more recent `-std=gnu++1y`, so I don't think that's it. Apparently macOS didn't introduce MAP_ANONYMOUS until 10.11, so I'm bumping the base mac version to that.

**Comment by minrk** [comment]
Success!

**Comment by blink1073** [comment]
:tada: thanks @minrk!

**Pull request merged**
