### PR TITLE
PR for v8.4.0

### PR DESCRIPTION
**Pull request by abhi18av**
This is a routine PR to update the `conda-forge` channel for a `node-8.x` series.

### CODE REVIEW

**Comment by abhi18av** [comment]
@minrk 
@msarahan 
@pelson 

Guys, could you help me out here ? :)

**Comment by pelson** [comment]
Thanks @abhi18av!

Could you comment on the reason for dropping windows support? That seems like a quite a big deal. 😕

**Comment by abhi18av** [comment]
Well, it wasn't building properly so I thought that perhaps that can be worked upon later but for now we need to update the feedstock first. 

It does need to maintain branches of the latest stable version of nodejs.

@pelson I'd need some help with the windows build since I don't have a windows dev machine close by .

**Comment by pelson** [comment]
For the record, the error on Windows was:

```
[00:31:09] C:\bld\nodejs_1508141353831\work\node-v8.4.0\tools\msvs\genfiles\node_perfctr_provider.h(50): warning C4838: conversion from 'unsigned long' to 'LONG' requires a narrowing conversion (compiling source file src\node_win32_perfctr_provider.cc) [C:\bld\nodejs_1508141353831\work\node-v8.4.0\cctest.vcxproj]
[00:31:09]   node_counters.cc
[00:31:09]   backtrace_win32.cc
[00:31:09] C:\bld\nodejs_1508141353831\work\node-v8.4.0\deps\v8\include\v8.h(4150): warning C4251: 'v8::WasmModuleObjectBuilder::received_buffers_': class 'std::vector<v8::WasmModuleObjectBuilder::Buffer,std::allocator<_Ty>>' needs to have dll-interface to be used by clients of class 'v8::WasmModuleObjectBuilder' [C:\bld\nodejs_1508141353831\work\node-v8.4.0\cctest.vcxproj]
[00:31:09]           with
[00:31:09]           [
[00:31:09]               _Ty=v8::WasmModuleObjectBuilder::Buffer
[00:31:09]           ] (compiling source file src\node_counters.cc)
[00:31:09]   C:\bld\nodejs_1508141353831\work\node-v8.4.0\deps\v8\include\v8.h(4150): note: see declaration of 'std::vector<v8::WasmModuleObjectBuilder::Buffer,std::allocator<_Ty>>'
[00:31:09]           with
[00:31:09]           [
[00:31:09]               _Ty=v8::WasmModuleObjectBuilder::Buffer
[00:31:09]           ] (compiling source file src\node_counters.cc)
[00:31:09] C:\bld\nodejs_1508141353831\work\node-v8.4.0\deps\v8\include\v8.h(4150): warning C4251: 'v8::WasmModuleObjectBuilder::received_buffers_': class 'std::vector<v8::WasmModuleObjectBuilder::Buffer,std::allocator<_Ty>>' needs to have dll-interface to be used by clients of class 'v8::WasmModuleObjectBuilder' [C:\bld\nodejs_1508141353831\work\node-v8.4.0\cctest.vcxproj]
[00:31:09]           with
[00:31:09]           [
[00:31:09]               _Ty=v8::WasmModuleObjectBuilder::Buffer
[00:31:09]           ] (compiling source file src\backtrace_win32.cc)
[00:31:09]   C:\bld\nodejs_1508141353831\work\node-v8.4.0\deps\v8\include\v8.h(4150): note: see declaration of 'std::vector<v8::WasmModuleObjectBuilder::Buffer,std::allocator<_Ty>>'
[00:31:09]           with
[00:31:09]           [
[00:31:09]               _Ty=v8::WasmModuleObjectBuilder::Buffer
[00:31:09]           ] (compiling source file src\backtrace_win32.cc)
[00:32:15]      Creating library C:\bld\nodejs_1508141353831\work\node-v8.4.0\Release\cctest.lib and object C:\bld\nodejs_1508141353831\work\node-v8.4.0\Release\cctest.exp
[00:32:15]   Generating code
[00:36:57] c:\bld\nodejs_1508141353831\work\node-v8.4.0\src\string_bytes.cc(767): warning C4715: 'node::StringBytes::Encode': not all control paths return a value [C:\bld\nodejs_1508141353831\work\node-v8.4.0\cctest.vcxproj]
[00:37:00]   Finished generating code
[00:37:10]   cctest.vcxproj -> C:\bld\nodejs_1508141353831\work\node-v8.4.0\Release\\cctest.exe
[00:37:10]   cctest.vcxproj -> C:\bld\nodejs_1508141353831\work\node-v8.4.0\Release\cctest.pdb (Full PDB)
[00:37:16]         1 file(s) copied.
[00:37:17] module.js:491
[00:37:17]     throw err;
[00:37:17]     ^
[00:37:17] 
[00:37:17] Error: Cannot find module 'C:\bld\nodejs_1508141353831\work\node-v8.4.0\deps\npm\cli.js'
[00:37:17]     at Function.Module._resolveFilename (module.js:489:15)
[00:37:17]     at Function.Module._load (module.js:439:25)
[00:37:17]     at Function.Module.runMain (module.js:609:10)
[00:37:17]     at startup (bootstrap_node.js:158:16)
[00:37:17]     at bootstrap_node.js:598:3
[00:37:17] Traceback (most recent call last):
[00:37:17]   File "C:\Miniconda\Scripts\conda-build-script.py", line 5, in <module>
[00:37:17]     sys.exit(conda_build.cli.main_build.main())
[00:37:17]   File "C:\Miniconda\lib\site-packages\conda_build\cli\main_build.py", line 342, in main
[00:37:17]     execute(sys.argv[1:])
[00:37:17]   File "C:\Miniconda\lib\site-packages\conda_build\cli\main_build.py", line 333, in execute
[00:37:17]     noverify=args.no_verify)
[00:37:17]   File "C:\Miniconda\lib\site-packages\conda_build\api.py", line 97, in build
[00:37:17]     need_source_download=need_source_download, config=config)
[00:37:17]   File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 1524, in build_tree
[00:37:17]     config=config)
[00:37:17]   File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 1114, in build
[00:37:17]     windows.build(m, build_file, config=config)
[00:37:17]   File "C:\Miniconda\lib\site-packages\conda_build\windows.py", line 231, in build
[00:37:17]     check_call_env(cmd, cwd=src_dir)
[00:37:17]   File "C:\Miniconda\lib\site-packages\conda_build\utils.py", line 628, in check_call_env
[00:37:17]     return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
[00:37:17]   File "C:\Miniconda\lib\site-packages\conda_build\utils.py", line 624, in _func_defaulting_env_to_os_environ
[00:37:17]     return func(_args, **kwargs)
[00:37:17]   File "C:\Miniconda\lib\subprocess.py", line 186, in check_call
[00:37:17]     raise CalledProcessError(retcode, cmd)
[00:37:17] subprocess.CalledProcessError: Command '['cmd.exe', '/c', 'bld.bat']' returned non-zero exit status 1
[00:37:20] Command exited with code 1
```

Looks like this might be a common issue after a quick search (though perhaps for an older node than the one here). The fix wasn't obvious though. I too lack a convenient Windows dev machine to put forward a solution to the problem.

**Comment by minrk** [comment]
finished up in #18

**Comment by abhi18av** [comment]
Thanks @minrk  👍

**Pull request closed without merging**
