### PR TITLE
Rebuild for icu {68,70}

### PR DESCRIPTION
**Pull request by lvoliveira**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by lvoliveira** [comment]
@conda-forge-admin, please rerender

**Comment by lvoliveira** [comment]
My intention was to build a package with no pined version for icu and openssl, but it seems this is not the proper way to do it. It is still generating a package with pinned version for the dependencies.

**Comment by xhochy** [comment]
The versions will always be pinned for icu and openssl as they are binary dependencies. You can build against multiple versions by specifying this in the `recipe/conda_build_config.yaml`. We currently don't get 14.x building against `openssl=3` see the respective PR here: https://github.com/conda-forge/nodejs-feedstock/pull/242

**Comment by lvoliveira** [comment]
Thanks @xhochy , I'll give it a try.

**Comment by lvoliveira** [comment]
@conda-forge-admin, please rerender

**Comment by lvoliveira** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
@conda-forge-admin, please ping team

**Review by xhochy — CHANGES_REQUESTED** [review]
This doesn't change anything in regards to OpenSSL but adds ICU to the matrix. The need for this is unclear to me.

**Comment by jakirkham** [comment]
Perhaps this was an attempt to address this comment ( https://github.com/conda-forge/nodejs-feedstock/pull/283#issuecomment-1278659051 ). Admittedly there may be some misunderstanding going on here. So some clarification around what is being suggested would likely help

**Comment by xhochy** [comment]
My understanding of this PR is that we want to have OpenSSL 3 builds. Otherwise, any changes here will be only cosmetic. To get OpenSSL 3 builds to work, one needs to add the migration and find a patch so `nodejs` actually compiles with it.

**Comment by lvoliveira** [comment]
I'm sorry for the misunderstanding. I will try to explain my needs and we can see if this PR still make sense. 

We have environment with pins for a lot of libraries, including icu and openssl. I was trying to update to the latest 14.* version of nodejs but conflicts appeared on the environment resolution. Just updating the pins requires a lot o work because is involves updating a big environment together with them. We are currently on a migration, but it will be a few (if not many) months before we can drop the older versions.

So I went to the recipe to see if it was possible to build the package compatible with our environment. My first guess looking tho the recipe was that the conflict was related to the pin on the openssl. But later on, after a better understanding of the way conda-forge manage the versions of the dependencies, I noticed the the problem was actually with the icu version. So, basically, I need this version of the nodejs build with icu 68, and that was what I changed on the recipe.

The name of the PR is really wrong now. I have named it based on my first assumption of the problem. 

That all being said, I await your opinion on what should be done with this PR.

**Comment by xhochy** [comment]
@lvoliveira Thanks for the explanation. This makes sense. Can you update the PR title? Then we can merge this.

**Comment by xhochy** [comment]
I can also edit the title :D

**Review by xhochy — APPROVED** [review]

**Pull request merged**
